apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
  namespace: cit-inpt
  labels:
    app: news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      containers:
        - name: news
          image: docker.io/aminerachyd/service-news:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: news
  namespace: cit-inpt
spec:
  selector:
    app: news
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
