apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: cit-inpt
  labels:
    app: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      containers:
        - name: weather
          image: docker.io/aminerachyd/service-weather:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: cit-inpt
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: LoadBalancer
